### Creating Dataframe
- Multiple series combined are termed as Dataframe

In [2]:
import numpy as np
import pandas as pd

#### From Dictionary

In [32]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Clever'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [33]:
df

     Name  Age      City  Salary
0    John   28  New York   65000
1    Anna   34     Paris   70000
2   Peter   29    Berlin   62000
3  Clever   42    London   85000

#### From List

In [ ]:
# When creating df from list, in list headers or column names are not mentioned, therefore by default every column is mentioned with 0,1,2,3,etc.

data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Clever', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
cols = ['Name','Age','City','Salary']
df2 = pd.DataFrame(data_list,columns=cols) # This mentions columns

In [6]:
df2

     Name  Age      City  Salary
0    John   28  New York   65000
1    Anna   34     Paris   70000
2   Peter   29    Berlin   62000
3  Clever   42    London   85000

### Selection and Indexing of Columns

In [7]:
df2

     Name  Age      City  Salary
0    John   28  New York   65000
1    Anna   34     Paris   70000
2   Peter   29    Berlin   62000
3  Clever   42    London   85000

In [10]:
# df2[0] --> Throws keyerror
df2['Name']
df2['Age']

0    28
1    34
2    29
3    42
Name: Age, dtype: int64

In [ ]:
df2[['Name','City']] # To get multiple columns, we provide list of columns

     Name      City
0    John  New York
1    Anna     Paris
2   Peter    Berlin
3  Clever    London

### Creating a new column

In [19]:
# Since there doesn't exist any Designation column, so it will create one and assign respective values

# Whenever we create column in this format, we have to pass exact no. of values in the list as there are no. of elements listed i.e. 4, otherwise it will throw error 

df2['Designation'] = ['Doctor', 'ML Engineer', 'Teacher', 'Doctor']

In [20]:
df2

     Name  Age      City  Salary  Designation
0    John   28  New York   65000       Doctor
1    Anna   34     Paris   70000  ML Engineer
2   Peter   29    Berlin   62000      Teacher
3  Clever   42    London   85000       Doctor

### Removing any Column

In [ ]:
# df2.drop('Designation') # Throws error --> "['Designation'] not found in axis"
df2.drop('Designation', axis=1) 
# By default Axis=0 searches out in row indices vertically --> horizontal drops 
# Axis=1 searches out in Column indices horizontally --> vertical drops

     Name  Age      City  Salary
0    John   28  New York   65000
1    Anna   34     Paris   70000
2   Peter   29    Berlin   62000
3  Clever   42    London   85000

In [ ]:
df2 # inplace=False --> Designation does not gets removed

     Name  Age      City  Salary  Designation
0    John   28  New York   65000       Doctor
1    Anna   34     Paris   70000  ML Engineer
2   Peter   29    Berlin   62000      Teacher
3  Clever   42    London   85000       Doctor

In [21]:
df2.drop('Designation', axis=1, inplace=True) #--> This removes column permanently
df2

     Name  Age      City  Salary
0    John   28  New York   65000
1    Anna   34     Paris   70000
2   Peter   29    Berlin   62000
3  Clever   42    London   85000

In [ ]:
# Removing multiple columns (vertical drops)
df2.drop(['City','Salary'], axis=1)

     Name  Age
0    John   28
1    Anna   34
2   Peter   29
3  Clever   42

In [24]:
# Removing row
# df2.drop('0') # Throws error -->  "['0'] not found in axis"
df2.drop(0)

     Name  Age    City  Salary
1    Anna   34   Paris   70000
2   Peter   29  Berlin   62000
3  Clever   42  London   85000

### Selecting Rows

In [25]:
df2

     Name  Age      City  Salary
0    John   28  New York   65000
1    Anna   34     Paris   70000
2   Peter   29    Berlin   62000
3  Clever   42    London   85000

In [ ]:
# df2[0] # Throws KeyError
df2.loc[[0,1]] # loc --> "location" or "label-based location access"

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [ ]:
df2.iloc[3]
# iloc --> "integer location" --> It is used for accessing rows or columns by their numeric position, not by label.
# loc --> uses labels
# iloc --> uses integer positions

Name      Clever
Age           42
City      London
Salary     85000
Name: 3, dtype: object

Selecting Subsets of Rows and Columns

In [38]:
df2

     Name  Age      City  Salary
0    John   28  New York   65000
1    Anna   34     Paris   70000
2   Peter   29    Berlin   62000
3  Clever   42    London   85000

In [ ]:
# First Rows are selected and then columns
df2.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [39]:
df2.loc[[2,3]][['Name','Salary']]

     Name  Salary
2   Peter   62000
3  Clever   85000

In [40]:
df2.loc[[1,2]][['Name','Age','Salary']]

    Name  Age  Salary
1   Anna   34   70000
2  Peter   29   62000

### Conditional Selection

In [41]:
df2

     Name  Age      City  Salary
0    John   28  New York   65000
1    Anna   34     Paris   70000
2   Peter   29    Berlin   62000
3  Clever   42    London   85000

In [ ]:
# People with age > 30

df2[df2['Age'] > 30]

     Name  Age    City  Salary
1    Anna   34   Paris   70000
3  Clever   42  London   85000

In [44]:
# People with age > 30 & City is Paris

# df2[df2['Age'] > 30 & df2['City'] == 'Paris'] # Throws error because these conditions are compared with Parenthesis
df2[(df2['Age'] > 30) & (df2['City'] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000