In [2]:
import numpy as np
import pandas as pd

## **Group By**
- Performed over categorical columns or qualitative columns

In [3]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [4]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [5]:
# Group By Category and calculate the sum of sales

cat = df.groupby(by='Category') # creates object which cannot be seen directly
cat # cannot be displayed directly

### **_Why GroupBy gives object but not dataframe representation with full data?_**

groupby() does not perform the grouping immediately. Instead, it creates a GroupBy object that stores the grouping instructions. This object waits until you specify what operation you want (such as sum(), mean(), count(), agg(), transform(), or filter()).

This approach is known as **lazy evaluation**.

**Why Doesn't Pandas Show the Data Immediately?**

- Because Pandas doesn't know what you want to do with the groups.

**What Does the GroupBy Object Actually Store?**

Internally, it stores information like:

- Original DataFrame
- Column(s) used for grouping
- Which rows belong to each group
- Metadata about the grouping

**Benefits of Creating a GroupBy Object**

- Grouping can be expensive for large datasets. 
- Instead of immediately calculating everything,
- Pandas waits until you ask.
- **Memory Efficiency**
    - The object stores references (like row indices) rather than duplicating the grouped data.

**Enables Split–Apply–Combine**

- groupby() is built around the classic Split–Apply–Combine strategy.
- The GroupBy object represents the split stage. Later methods perform the apply and combine stages.

In [6]:
for i, v in cat:
    print(i)
    print(v)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [7]:
# Group by Category and calculate the sum of Sales
cat = df.groupby(by='Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [8]:
# Group by Store and calculate the sum of Sales
cat = df.groupby(by='Store')['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [9]:
# Group by multiple columns
# Group by Category and Store
cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

## **Aggregation**

- Aggregation in Pandas means combining multiple values from a dataset and producing a single summary value using functions such as sum(), mean(), min(), max(), count(), etc.

In [10]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [11]:
df['Sales'].mean()

np.float64(187.5)

In [12]:
df['Sales'].median()

190.0

In [13]:
# count(),std(),mode() #Using mode() with agg() gives error

Aggregation functions are generally expected to reduce many values into a single value. mode() may return multiple values, so it does not behave as a standard scalar aggregation function in this context.

In [14]:
# df['Sales'].agg(['mean','median','mode','count','std']) # throws error due to mode()
df['Sales'].agg(['mean','median','count','std'])

mean      187.500000
median    190.000000
count       8.000000
std        66.062741
Name: Sales, dtype: float64

In [15]:
df['Sales'].mode()

0    200
Name: Sales, dtype: int64