In [1]:
import numpy  as np
import pandas as pd

## **Pivot Tables**

A pivot table summarizes data by organizing one or more categorical variables into rows and columns and applying an aggregation function to numerical data.
- **"Group my data by these row and column categories, then calculate something."**
- Used in creation of heatmaps
- Aggregation Functions are used in operation or calculation
- Aggregation-oriented Summary

In [2]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

In [4]:
df['Month'] = df['Date'].dt.month_name()
df.head()

        Date Product Region  Sales  Units    Rep    Month
0 2023-01-01       A   East    753     51   John  January
1 2023-01-02       B   West    844     50   Mary  January
2 2023-01-03       C  North    559     79    Bob  January
3 2023-01-04       D  South    535     91  Alice  January
4 2023-01-05       A   East    156     11   John  January

In [9]:
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df.head()

        Date Product Region  Sales  Units    Rep    Month Quarter
0 2023-01-01       A   East    753     51   John  January      Q1
1 2023-01-02       B   West    844     50   Mary  January      Q1
2 2023-01-03       C  North    559     79    Bob  January      Q1
3 2023-01-04       D  South    535     91  Alice  January      Q1
4 2023-01-05       A   East    156     11   John  January      Q1

In [6]:
df['Date'].dt.quarter.head()

0    1
1    1
2    1
3    1
4    1
Name: Date, dtype: int32

In [7]:
df['Date'].dt.quarter.astype(str).head()

0    1
1    1
2    1
3    1
4    1
Name: Date, dtype: object

In [10]:
# 'Q' + 1
'Q' + '1'

'Q1'

In [11]:
df.head()

        Date Product Region  Sales  Units    Rep    Month Quarter
0 2023-01-01       A   East    753     51   John  January      Q1
1 2023-01-02       B   West    844     50   Mary  January      Q1
2 2023-01-03       C  North    559     79    Bob  January      Q1
3 2023-01-04       D  South    535     91  Alice  January      Q1
4 2023-01-05       A   East    156     11   John  January      Q1

**Note:** In a function definition, wherever there are parameters marked as None are required to be filled

In [13]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product')

Product      A      B      C      D
Region
East     576.8    NaN    NaN    NaN
North      NaN    NaN  470.6    NaN
South      NaN    NaN    NaN  358.8
West       NaN  649.8    NaN    NaN

In [15]:
pivot1 = pd.pivot_table(df,values='Sales',index='Region',columns='Product',aggfunc='median')
pivot1

Product      A      B      C      D
Region
East     675.0    NaN    NaN    NaN
North      NaN    NaN  559.0    NaN
South      NaN    NaN    NaN  332.0
West       NaN  755.0    NaN    NaN

In [18]:
pivot2 = pd.pivot_table(df,values=['Sales','Units'],index='Region',columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     576.8    NaN    NaN    NaN  39.2   NaN   NaN   NaN
North      NaN    NaN  470.6    NaN   NaN   NaN  57.2   NaN
South      NaN    NaN    NaN  358.8   NaN   NaN   NaN  70.8
West       NaN  649.8    NaN    NaN   NaN  52.6   NaN   NaN

In [ ]:
# This gives error because Pivot Tables uses aggfunc() in operation where only numerical data is used
pivot2 = pd.pivot_table(df,values=['Sales','Quarter'],index='Region',columns='Product')
pivot2

## **Cross Tabs**

A crosstab, short for cross-tabulation, is primarily used to calculate the frequency or count of combinations of categorical variables.
- **"Tell me how often these two categories occur together."**
- Counting is used in calculation
- Frequency-oriented Summary

In [19]:
df.head()

        Date Product Region  Sales  Units    Rep    Month Quarter
0 2023-01-01       A   East    753     51   John  January      Q1
1 2023-01-02       B   West    844     50   Mary  January      Q1
2 2023-01-03       C  North    559     79    Bob  January      Q1
3 2023-01-04       D  South    535     91  Alice  January      Q1
4 2023-01-05       A   East    156     11   John  January      Q1

In [ ]:
pd.crosstab(df['Region'],df['Product'])

# The key distinction is: df[['Region', 'Product']] means "select these two columns," whereas pd.crosstab(df['Region'], df['Product']) means "use Region as the row variable and Product as the column variable."
# df['Region']   # First Series → used as rows
# df['Product']  # Second Series → used as columns

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0