In [13]:
import numpy as np
import pandas as pd

In [14]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Clever'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [15]:
df

     Name  Age      City  Salary
0    John   28  New York   65000
1    Anna   34     Paris   70000
2   Peter   29    Berlin   62000
3  Clever   42    London   85000

In [16]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Clever', 42, 'London', 85000]
]
data_list

[['John', 28, 'New York', 65000],
 ['Anna', 34, 'Paris', 70000],
 ['Peter', 29, 'Berlin', 62000],
 ['Clever', 42, 'London', 85000]]

In [17]:
df2 = pd.DataFrame(data_list)
cols = ['Name', 'Age', 'City', 'Salary']
df2 = pd.DataFrame(data_list, columns=cols)
df2

     Name  Age      City  Salary
0    John   28  New York   65000
1    Anna   34     Paris   70000
2   Peter   29    Berlin   62000
3  Clever   42    London   85000

In [18]:
df2

     Name  Age      City  Salary
0    John   28  New York   65000
1    Anna   34     Paris   70000
2   Peter   29    Berlin   62000
3  Clever   42    London   85000

In [19]:
df2['Name']
df2['City']

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

In [20]:
df2[['Name','City']] # To get multiple columns, we provide list of columns

     Name      City
0    John  New York
1    Anna     Paris
2   Peter    Berlin
3  Clever    London

Creating a New Column

In [21]:
df2['Designation'] = ['Doctor', 'ML Engineer', 'Teacher', 'Doctor']

In [22]:
df

     Name  Age      City  Salary
0    John   28  New York   65000
1    Anna   34     Paris   70000
2   Peter   29    Berlin   62000
3  Clever   42    London   85000

Removing a Column

In [39]:
df2

     Name  Age      City  Salary  Designation
0    John   28  New York   65000       Doctor
1    Anna   34     Paris   70000  ML Engineer
2   Peter   29    Berlin   62000      Teacher
3  Clever   42    London   85000       Doctor

In [42]:
df2.drop(0, axis=0)

     Name  Age    City  Salary  Designation
1    Anna   34   Paris   70000  ML Engineer
2   Peter   29  Berlin   62000      Teacher
3  Clever   42  London   85000       Doctor

In [24]:
df2.drop(['City','Salary'], axis=1)

     Name  Age  Designation
0    John   28       Doctor
1    Anna   34  ML Engineer
2   Peter   29      Teacher
3  Clever   42       Doctor

In [25]:
df2.drop(0)

     Name  Age    City  Salary  Designation
1    Anna   34   Paris   70000  ML Engineer
2   Peter   29  Berlin   62000      Teacher
3  Clever   42  London   85000       Doctor

Selecting Rows

In [26]:
df2

     Name  Age      City  Salary  Designation
0    John   28  New York   65000       Doctor
1    Anna   34     Paris   70000  ML Engineer
2   Peter   29    Berlin   62000      Teacher
3  Clever   42    London   85000       Doctor

In [27]:
# df2[0] # Throws Keyerror
df2.loc[[0,1]] # label-based location access

   Name  Age      City  Salary  Designation
0  John   28  New York   65000       Doctor
1  Anna   34     Paris   70000  ML Engineer

In [28]:
df3 = df2.copy() # Deep copy
df3.index = ['A','B','C','D']
df3

     Name  Age      City  Salary  Designation
A    John   28  New York   65000       Doctor
B    Anna   34     Paris   70000  ML Engineer
C   Peter   29    Berlin   62000      Teacher
D  Clever   42    London   85000       Doctor

In [29]:
df3.loc['B'] # Label based

Name                  Anna
Age                     34
City                 Paris
Salary               70000
Designation    ML Engineer
Name: B, dtype: object

In [30]:
df3.iloc[1] # Integer Based

Name                  Anna
Age                     34
City                 Paris
Salary               70000
Designation    ML Engineer
Name: B, dtype: object

In [31]:
df2

     Name  Age      City  Salary  Designation
0    John   28  New York   65000       Doctor
1    Anna   34     Paris   70000  ML Engineer
2   Peter   29    Berlin   62000      Teacher
3  Clever   42    London   85000       Doctor

In [32]:
df2.loc[[1,2]][['Name','Salary']]

    Name  Salary
1   Anna   70000
2  Peter   62000

In [33]:
df2.loc[[1,2], ['Name', 'Salary']]

    Name  Salary
1   Anna   70000
2  Peter   62000

Conditional Selection

In [34]:
df2

     Name  Age      City  Salary  Designation
0    John   28  New York   65000       Doctor
1    Anna   34     Paris   70000  ML Engineer
2   Peter   29    Berlin   62000      Teacher
3  Clever   42    London   85000       Doctor

In [35]:
# People with age > 30

df2[df2['Age'] > 30]

     Name  Age    City  Salary  Designation
1    Anna   34   Paris   70000  ML Engineer
3  Clever   42  London   85000       Doctor

In [36]:
df2

     Name  Age      City  Salary  Designation
0    John   28  New York   65000       Doctor
1    Anna   34     Paris   70000  ML Engineer
2   Peter   29    Berlin   62000      Teacher
3  Clever   42    London   85000       Doctor

In [37]:
# People with age > 30 & Salary > 70000

df2[(df2['Age'] > 30) & (df2['Salary'] > 70000)]

     Name  Age    City  Salary Designation
3  Clever   42  London   85000      Doctor

In [38]:
df2[(df2['Age'] > 30) & (df2['City'] == 'London')]

     Name  Age    City  Salary Designation
3  Clever   42  London   85000      Doctor