In [1]:
import numpy as np
import pandas as pd

## **Basic Operations**

In [27]:
df1 = pd.DataFrame({
    'A': [1,2,3,4,5],
    'B': [10,20,30,40,np.nan],
    'C': [100,200,np.nan,400,np.nan]
})

In [8]:
df1

   A     B      C
0  1  10.0  100.0
1  2  20.0  200.0
2  3  30.0    NaN
3  4  40.0  400.0
4  5   NaN    NaN

In [4]:
df1.shape

(5, 3)

In [5]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [16]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       4 non-null      float64
 2   C       3 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 252.0 bytes

In [13]:
df1

   A     B      C
0  1  10.0  100.0
1  2  20.0  200.0
2  3  30.0    NaN
3  4  40.0  400.0
4  5   NaN    NaN

In [15]:
df1.describe()

              A          B           C
count  5.000000   4.000000    3.000000
mean   3.000000  25.000000  233.333333
std    1.581139  12.909944  152.752523
min    1.000000  10.000000  100.000000
25%    2.000000  17.500000  150.000000
50%    3.000000  25.000000  200.000000
75%    4.000000  32.500000  300.000000
max    5.000000  40.000000  400.000000

In [ ]:
# Broadcasting
df1['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

## **Applying Functions**

In [26]:
df1

   A          B      C
0  1    10000.0  100.0
1  2   160000.0  200.0
2  3   810000.0    NaN
3  4  2560000.0  400.0
4  5        NaN    NaN

Square the elements of column B

In [28]:
def square(x: int):
    return x**2

In [21]:
df1['B'].apply(square)

0     100.0
1     400.0
2     900.0
3    1600.0
4       NaN
Name: B, dtype: float64

In [30]:
# df1['B'] = df1['B'].apply(square)
df1['D'] = df1['B'].apply(square)

In [31]:
df1

   A     B      C       D
0  1  10.0  100.0   100.0
1  2  20.0  200.0   400.0
2  3  30.0    NaN   900.0
3  4  40.0  400.0  1600.0
4  5   NaN    NaN     NaN