In [1]:
import numpy as np
import pandas as pd

## **Pivot Tables**

In [2]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

In [6]:
df.head()

        Date Product Region  Sales  Units    Rep
0 2023-01-01       A   East    763     58   John
1 2023-01-02       B   West    129     73   Mary
2 2023-01-03       C  North    237     39    Bob
3 2023-01-04       D  South    247     78  Alice
4 2023-01-05       A   East    559     73   John

In [9]:
df['Month'] = df['Date'].dt.month_name()
df.head()

        Date Product Region  Sales  Units    Rep    Month
0 2023-01-01       A   East    763     58   John  January
1 2023-01-02       B   West    129     73   Mary  January
2 2023-01-03       C  North    237     39    Bob  January
3 2023-01-04       D  South    247     78  Alice  January
4 2023-01-05       A   East    559     73   John  January

In [12]:
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df.head()

        Date Product Region  Sales  Units    Rep    Month Quarter
0 2023-01-01       A   East    763     58   John  January      Q1
1 2023-01-02       B   West    129     73   Mary  January      Q1
2 2023-01-03       C  North    237     39    Bob  January      Q1
3 2023-01-04       D  South    247     78  Alice  January      Q1
4 2023-01-05       A   East    559     73   John  January      Q1

In [ ]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product')

Product      A      B      C      D
Region
East     698.2    NaN    NaN    NaN
North      NaN    NaN  410.4    NaN
South      NaN    NaN    NaN  494.4
West       NaN  479.0    NaN    NaN

In [16]:
pivot1 = pd.pivot_table(df,values='Sales',index='Region',columns='Product',aggfunc='median')
pivot1

Product      A      B      C      D
Region
East     647.0    NaN    NaN    NaN
North      NaN    NaN  360.0    NaN
South      NaN    NaN    NaN  599.0
West       NaN  582.0    NaN    NaN

In [18]:
pivot2 = pd.pivot_table(df,values=['Sales','Units'],index='Region',columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     698.2    NaN    NaN    NaN  63.8   NaN   NaN   NaN
North      NaN    NaN  410.4    NaN   NaN   NaN  62.2   NaN
South      NaN    NaN    NaN  494.4   NaN   NaN   NaN  64.4
West       NaN  479.0    NaN    NaN   NaN  44.6   NaN   NaN

In [22]:
df.head()

        Date Product Region  Sales  Units    Rep    Month Quarter
0 2023-01-01       A   East    763     58   John  January      Q1
1 2023-01-02       B   West    129     73   Mary  January      Q1
2 2023-01-03       C  North    237     39    Bob  January      Q1
3 2023-01-04       D  South    247     78  Alice  January      Q1
4 2023-01-05       A   East    559     73   John  January      Q1

In [ ]:
# This gives error because Pivot Tables uses aggfunc() in operation where only numerical data is used
# pivot2 = pd.pivot_table(df,values=['Sales','Quarter'],index='Region',columns='Product')
# pivot2

## **Cross Tabs**

In [23]:
df.head()

        Date Product Region  Sales  Units    Rep    Month Quarter
0 2023-01-01       A   East    763     58   John  January      Q1
1 2023-01-02       B   West    129     73   Mary  January      Q1
2 2023-01-03       C  North    237     39    Bob  January      Q1
3 2023-01-04       D  South    247     78  Alice  January      Q1
4 2023-01-05       A   East    559     73   John  January      Q1

In [ ]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [ ]:
# df[['Region','Product']] --> 'select these two columns'
# pd.crosstab(df['Region'],df['Product']) 
# pd.crosstab(,df['Product']) 
# df['Region'] --> #First Series --> used as rows
# df['Product'] --> #Second Series --> used as columns